package com.hadi.clarpse.compiler.csharp;

import com.hadi.clarpse.compiler.CompilerSupport;
import com.hadi.clarpse.compiler.ProjectFile;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Pattern;

/**
 * The types every C# file of the repository declares, read by {@link CSharpDeclarationScanner}
 * without parsing, and the files that matter to name resolution everywhere.
 *
 * <p>It answers which files declare a type, whether the repository declares a name at all, which
 * files hold the other parts of a partial type, and which files carry {@code global using}
 * directives. It also builds declaration-only stub file models, through which the C# assembler
 * resolves names against the whole repository while parsing only a few files.
 *
 * <p>When a type is declared both in files marked {@code <auto-generated>} and in files that are
 * not, only the latter count as declaring it. Generated files commonly redeclare a project's public
 * surface, and counting them would pull every such file into a one-level analysis.
 */
final class CSharpDeclarationIndex {

    private static final Pattern GLOBAL_USING = Pattern.compile("(?m)^\\s*global\\s+using\\s");

    /** How much of a file's head is searched for the generated-code marker. */
    private static final int GENERATED_MARKER_WINDOW = 2048;

    private final Map<String, ProjectFile> filesByPath = new LinkedHashMap<>();
    private final Map<String, List<CSharpDeclarationScanner.Declaration>> declarationsByFile = new HashMap<>();
    private final Map<String, Set<String>> filesByUniqueName = new HashMap<>();
    private final Set<String> generatedFiles = new TreeSet<>();
    private final Set<String> globalUsingFiles = new TreeSet<>();

    CSharpDeclarationIndex(final Collection<ProjectFile> files) {
        for (final ProjectFile file : files) {
            if (file.path() == null) {
                continue;
            }
            final String content = file.content();
            filesByPath.put(file.path(), file);
            final List<CSharpDeclarationScanner.Declaration> declarations = CSharpDeclarationScanner.scan(content);
            declarationsByFile.put(file.path(), declarations);
            for (final CSharpDeclarationScanner.Declaration declaration : declarations) {
                filesByUniqueName.computeIfAbsent(declaration.uniqueName(), key -> new TreeSet<>()).add(file.path());
            }
            if (content != null) {
                if (content.substring(0, Math.min(content.length(), GENERATED_MARKER_WINDOW))
                        .contains("<auto-generated")) {
                    generatedFiles.add(file.path());
                }
                if (GLOBAL_USING.matcher(content).find()) {
                    globalUsingFiles.add(file.path());
                }
            }
        }
    }

    /**
     * The declared type a referenced name falls under: the name itself when a file declares it,
     * otherwise its longest declared prefix, so a member's name leads to its type.
     *
     * @param name A referenced name, possibly of a member with a signature.
     * @return The declared unique name, or {@code null} when the repository declares none.
     */
    String declaredTypeOf(final String name) {
        String candidate = name;
        while (candidate != null && !candidate.isEmpty()) {
            if (filesByUniqueName.containsKey(candidate)) {
                return candidate;
            }
            String head = candidate;
            final int paren = head.indexOf('(');
            if (paren >= 0) {
                head = head.substring(0, paren);
            }
            final int dot = head.lastIndexOf('.');
            if (dot < 0) {
                return null;
            }
            candidate = head.substring(0, dot);
        }
        return null;
    }

    /**
     * Whether the repository declares the type a referenced name falls under.
     *
     * @param name A referenced name.
     * @return {@code true} when some file declares it.
     */
    boolean declares(final String name) {
        return declaredTypeOf(name) != null;
    }

    /**
     * The files declaring the type a referenced name falls under, generated files only when no
     * other file declares it.
     *
     * @param name A referenced name.
     * @return The files' paths, sorted; empty when the repository declares no such type.
     */
    Set<String> filesDeclaring(final String name) {
        final String type = declaredTypeOf(name);
        if (type == null) {
            return Set.of();
        }
        return preferHandWritten(filesByUniqueName.get(type));
    }

    /**
     * The files holding the other parts of the partial types a file declares.
     *
     * @param path A file's path.
     * @return The other parts' files, sorted, generated files only when no other file holds a part.
     */
    Set<String> partialParts(final String path) {
        final Set<String> parts = new TreeSet<>();
        for (final CSharpDeclarationScanner.Declaration declaration
                : declarationsByFile.getOrDefault(path, List.of())) {
            if (declaration.partial()) {
                parts.addAll(preferHandWritten(filesByUniqueName.get(declaration.uniqueName())));
            }
        }
        parts.remove(path);
        return parts;
    }

    private Set<String> preferHandWritten(final Set<String> paths) {
        final Set<String> handWritten = new TreeSet<>();
        for (final String path : paths) {
            if (!generatedFiles.contains(path)) {
                handWritten.add(path);
            }
        }
        if (handWritten.isEmpty()) {
            return Collections.unmodifiableSet(paths);
        }
        return handWritten;
    }

    /**
     * The files carrying {@code global using} directives, which apply to every file of a project.
     *
     * @return The files' paths, sorted.
     */
    Set<String> globalUsingFiles() {
        return Collections.unmodifiableSet(globalUsingFiles);
    }

    /**
     * A declaration-only file model for every file not among {@code excluded}: its types, nested
     * where they are nested, with no members, usings or references.
     *
     * @param excluded Paths of files that are parsed instead.
     * @return The stub file models.
     */
    List<CSharpModel.CSharpFileModel> stubs(final Set<String> excluded) {
        final List<CSharpModel.CSharpFileModel> stubs = new ArrayList<>();
        for (final Map.Entry<String, ProjectFile> entry : filesByPath.entrySet()) {
            final List<CSharpDeclarationScanner.Declaration> declarations = declarationsByFile.get(entry.getKey());
            if (excluded.contains(entry.getKey()) || declarations.isEmpty()) {
                continue;
            }
            stubs.add(stub(entry.getValue(), declarations));
        }
        return stubs;
    }

    private static CSharpModel.CSharpFileModel stub(final ProjectFile file,
                                                    final List<CSharpDeclarationScanner.Declaration> declarations) {
        final CSharpModel.CSharpFileModel fileModel =
                new CSharpModel.CSharpFileModel(file, null, CompilerSupport.moduleNameForFile(file.path()));
        final Map<String, CSharpModel.CSharpTypeModel> byComponentName = new HashMap<>();
        final List<CSharpDeclarationScanner.Declaration> outermostFirst = new ArrayList<>(declarations);
        outermostFirst.sort(Comparator.comparingInt(declaration -> declaration.componentName().split("\\.").length));
        for (final CSharpDeclarationScanner.Declaration declaration : outermostFirst) {
            final CSharpModel.CSharpTypeModel typeModel = new CSharpModel.CSharpTypeModel();
            typeModel.kind = declaration.kind();
            typeModel.name = declaration.name();
            typeModel.namespaceName = declaration.namespaceName();
            typeModel.moduleName = fileModel.moduleName;
            typeModel.sourcePath = file.path();
            typeModel.partial = declaration.partial();
            typeModel.componentName = declaration.componentName();
            final int dot = declaration.componentName().lastIndexOf('.');
            if (dot < 0) {
                fileModel.types.add(typeModel);
            } else {
                final CSharpModel.CSharpTypeModel parent =
                        byComponentName.get(declaration.componentName().substring(0, dot));
                if (parent == null) {
                    continue;
                }
                parent.nestedTypes.add(typeModel);
            }
            byComponentName.putIfAbsent(declaration.componentName(), typeModel);
        }
        return fileModel;
    }
}
