package com.hadi.test.onelevel;

import com.hadi.clarpse.compiler.AnalysisOptions;
import com.hadi.clarpse.compiler.ClarpseProject;
import com.hadi.clarpse.compiler.CompileResult;
import com.hadi.clarpse.compiler.Lang;
import com.hadi.clarpse.sourcemodel.Component;
import com.hadi.clarpse.sourcemodel.OOPSourceCodeModel;
import org.junit.BeforeClass;
import org.junit.Test;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import static com.hadi.test.onelevel.OneLevelTestSupport.component;
import static com.hadi.test.onelevel.OneLevelTestSupport.componentsOf;
import static com.hadi.test.onelevel.OneLevelTestSupport.files;
import static com.hadi.test.onelevel.OneLevelTestSupport.json;
import static com.hadi.test.onelevel.OneLevelTestSupport.project;
import static com.hadi.test.onelevel.OneLevelTestSupport.referencePairs;
import static com.hadi.test.onelevel.OneLevelTestSupport.targets;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

/**
 * One-level analysis of C#: names resolve against the whole repository through a declaration index,
 * and level one is the set of files declaring what the analysed file references.
 */
public class CSharpOneLevelTest {

    private static final String A = "/Core/A.cs";
    private static final String A_PART = "/Core/A.Part.cs";
    private static final String B = "/Lib/B.cs";
    private static final String SHAPE = "/Lib/Shape.cs";
    private static final String OUTER = "/Lib/Outer.cs";
    private static final String EXTRA = "/Lib/Extra.cs";
    private static final String EXTRA_MORE = "/Lib/Extra.More.cs";
    private static final String C = "/Deep/C.cs";
    private static final String REMOTE = "/Other/Remote.cs";
    private static final String GENERATED_REMOTE = "/Generated/Remote.g.cs";
    private static final String HELPER = "/Util/Helper.cs";
    private static final String GLOBAL_USINGS = "/GlobalUsings.cs";

    private static CompileResult oneLevel;
    private static OOPSourceCodeModel whole;

    static Map<String, String> repository() {
        return files(
                A, "using Lib;\nusing Other;\n"
                        + "namespace App\n{\n    public partial class A : B\n    {\n"
                        + "        public Shape Shape;\n        public Remote Remote;\n"
                        + "        public Outer.Inner Inner;\n        public Helper Helper;\n    }\n}\n",
                A_PART, "using Lib;\nnamespace App\n{\n    public partial class A\n    {\n"
                        + "        public Extra Extra;\n    }\n}\n",
                B, "using Deep;\nnamespace Lib\n{\n    public class B\n    {\n        public C C;\n    }\n}\n",
                SHAPE, "namespace Lib\n{\n    public class Shape { }\n}\n",
                OUTER, "namespace Lib\n{\n    public class Outer\n    {\n        public class Inner { }\n    }\n}\n",
                EXTRA, "namespace Lib;\npublic partial class Extra { }\n",
                EXTRA_MORE, "namespace Lib\n{\n    public partial class Extra\n    {\n        public int Size;\n    }\n}\n",
                C, "namespace Deep\n{\n    public class C { }\n}\n",
                REMOTE, "namespace Other\n{\n    public class Remote { }\n}\n",
                GENERATED_REMOTE, "// <auto-generated/>\nnamespace Other\n{\n    public class Remote { }\n}\n",
                HELPER, "namespace Util\n{\n    public class Helper { }\n}\n",
                GLOBAL_USINGS, "global using Util;\n",
                "/Unrelated.cs", "namespace App\n{\n    public class Unrelated { }\n}\n");
    }

    @BeforeClass
    public static void compile() throws Exception {
        oneLevel = new ClarpseProject(project(repository()), Lang.CSHARP, List.of(A),
                AnalysisOptions.oneLevel()).result();
        whole = new ClarpseProject(project(repository()), Lang.CSHARP).result().model();
    }

    @Test
    public void levelOneIsDeclaringFilesWithPartialPartsAndHandWrittenOverGenerated() {
        assertEquals(new TreeSet<>(Set.of(B, SHAPE, OUTER, EXTRA, EXTRA_MORE, REMOTE, HELPER)),
                new TreeSet<>(oneLevel.levelOne().levelOneFiles()));
    }

    @Test
    public void partsOfAnAnalysedPartialTypeAreAnalysedToo() {
        final Component a = component(oneLevel.model(), "App.A");
        assertFalse(a.isBoundary());
        assertTrue(oneLevel.model().containsComponent("App.A.Extra"));
        assertFalse(component(oneLevel.model(), "App.A.Extra").isBoundary());
    }

    @Test
    public void levelOneComponentsAreBoundaryAndNothingBeyondIsModelled() {
        final OOPSourceCodeModel model = oneLevel.model();
        for (final String name : List.of("Lib.B", "Lib.Shape", "Lib.Outer", "Lib.Outer.Inner", "Lib.Extra",
                "Other.Remote", "Util.Helper")) {
            assertTrue(name, component(model, name).isBoundary());
        }
        assertTrue(model.containsComponent("Lib.Extra.Size"));
        assertFalse(model.containsComponent("Deep.C"));
        assertFalse(model.containsComponent("App.Unrelated"));
    }

    @Test
    public void analysedReferencesResolveThroughUsingsGlobalUsingsAndNesting() {
        final Set<String> internal = new TreeSet<>();
        oneLevel.model().components()
                .filter(c -> c.uniqueName().startsWith("App.A"))
                .forEach(c -> internal.addAll(targets(c.internalDependencies())));
        assertTrue(internal.toString(), internal.containsAll(Set.of("Lib.B", "Lib.Shape", "Other.Remote",
                "Lib.Outer.Inner", "Util.Helper", "Lib.Extra")));
    }

    @Test
    public void boundaryReferencesPastLevelOneAreNotLoaded() {
        final Component field = component(oneLevel.model(), "Lib.B.C");
        assertEquals(Set.of("Deep.C"), targets(field.notLoadedDependencies()));
        assertTrue(field.externalDependencies().isEmpty());
    }

    @Test
    public void analysedReferencesEqualThoseOfWholeRepositoryAnalysis() {
        assertEquals(referencePairs(whole, List.of(A, A_PART)), referencePairs(oneLevel.model(), List.of(A, A_PART)));
        assertEquals(componentsOf(whole, List.of(B, OUTER)), componentsOf(oneLevel.model(), List.of(B, OUTER)));
    }

    @Test
    public void budgetHoldsLevelOneFilesBack() throws Exception {
        final CompileResult held = new ClarpseProject(project(repository()), Lang.CSHARP, List.of(A),
                AnalysisOptions.oneLevel().withLevelOneBudget(3)).result();
        assertEquals(3, held.levelOne().levelOneFiles().size());
        assertEquals(4, held.levelOne().heldByBudget().size());
        final Set<String> notLoaded = new TreeSet<>();
        held.model().components().forEach(c -> notLoaded.addAll(targets(c.notLoadedDependencies())));
        assertFalse(notLoaded.isEmpty());
    }

    @Test
    public void levelOneFilesCanBeDiscoveredWithoutModelling() throws Exception {
        assertEquals(new TreeSet<>(Set.of(B, SHAPE, OUTER, EXTRA, EXTRA_MORE, REMOTE, HELPER)),
                OneLevelTestSupport.discovered(repository(), Lang.CSHARP, List.of(A)));
    }

    /** Preparing, reading level one and completing gives the model a direct compile gives. */
    @Test
    public void aPreparedAnalysisCompletesToTheDirectCompile() throws Exception {
        final CompileResult[] both = OneLevelTestSupport.unionCompile(repository(), repository(), Lang.CSHARP,
                List.of(A));
        assertEquals(json(oneLevel.model()), json(both[0].model()));
        assertEquals(oneLevel.levelOne().levelOneFiles(), both[1].levelOne().levelOneFiles());
    }

    @Test
    public void defaultModeIsUnchangedByTheOptionsApi() throws Exception {
        final OOPSourceCodeModel plain = new ClarpseProject(project(repository()), Lang.CSHARP, List.of(A))
                .result().model();
        final OOPSourceCodeModel full = new ClarpseProject(project(repository()), Lang.CSHARP, List.of(A),
                AnalysisOptions.full()).result().model();
        assertEquals(json(plain), json(full));
    }
}
